### ISSUE TITLE
Update K definition (Eq. 2) to account for Fast Convergence

### ISSUE THREAD

**Issue by WesleyRosenblum** [NTAP/rfc8312bis#1]
As discussed in [this tcpm thread](https://mailarchive.ietf.org/arch/msg/tcpm/O7Q55oXcoI1XNBZ_wAQOMdhRQNY/), after fast convergence (section 4.6), the candidate target value of the congestion window may be less than the current congestion window. For example, say cwnd = 100, beta_cubic = .7 and a congestion event occurs:

```
W_max = cwnd = 100;
W_max = W_max*(1.0+beta_cubic)/2.0 = 85   // further reduce W_max for fast convergence

cwnd = cwnd * beta_cubic = 70	          // window reduction
W_cubic(0) = W_max * beta_cubic = 59.5
```

If we were to enter congestion avoidance at this point, with a small enough RTT, the candidate target congestion window as calculated by W_cubic(t+RTT) may be less than the current congestion window (~59.5 < 70). 

The suggestion in the thread from Lisong Xu and Vidhi Goel is to change Equation 2 to:
```
K = cubic_root((W_max - cwnd)/C) (Eq. 2)
```
where cwnd is the congestion window size at the beginning of the current congestion avoidance. This will ensure the target is greater than the current congestion window, and in my opinion is a more clear representation of what K represents.

**Comment by lisongxu** [comment]
Yes, we can change Equation 2 in the RFC to the following equation where cwnd is the cwnd at the beginning of the current congestion avoidance stage. 

`
K = cubic_root((W_max - cwnd)/C)  (Eq. 2)
`

To be exactly consistent with the Linux Cubic implementation, we can change Equation 2 to the following statement, where cwnd is still the cwnd at the beginning of the current congestion avoidance stage. 

`
if (cwnd < W_max)
  K = cubic_root((W_max - cwnd)/C)  
else{
  K = 0  
  W_max = cwnd
}

`

Thank you!

**Comment by larseggert** [comment]
@lisongxu thanks for confirming that Linux is doing something very similar! We should poll other implementors to see if they are already doing this, or would start to if we were to make this change.

@goelvidhi could you update the PR accordingly?

**Comment by goelvidhi** [comment]
@lisongxu, in the below equation, setting W_max = cwnd seems superfluous. Also, next time we want to compute K, it will enter the first condition and end up with K = 0.
```if (cwnd < W_max)
K = cubic_root((W_max - cwnd)/C)
else{
K = 0
W_max = cwnd
}

**Comment by sangtaeha** [comment]
@lisongxu We may remove W_max = cwnd under the else {} since this is about how we compute K? Sections on convex and concave regions already explained what happens when cwnd is greater than equal to Wmax.

**Comment by lisongxu** [comment]
We calculate K only once at the beginning of a congestion avoidance stage.  

Statement "W_max = cwnd" corresponds to line 249 of [https://github.com/torvalds/linux/blob/master/net/ipv4/tcp_cubic.c#L249](url).  Without this statement, the new cwnd calculated at t=0 using Equation (1) would be even lower than the current cwnd.
`
W_cubic(t) = C*(t-K)^3 + W_max (Eq. 1)
`

But I agree that we should not change W_max, as W_max is also used by fast convergence. 

Maybe we should introduce a new variable origin_point as Linux does. 

At the beginning of a congestion avoidance stage, we set the value of K and origin_point as follows

```
if (cwnd < W_max)
{
    K = cubic_root((W_max - cwnd)/C)
    origin_point = W_max
}
else
{
    K = 0
    origin_point = cwnd
}
```

During the congestion avoidance stage, we calculate cwnd as follows

`
W_cubic(t) = C*(t-K)^3 + origin_point (Eq. 1)
`

**Comment by sangtaeha** [comment]
I agree. Yes, without a new variable, it is hard. Now, it is closer to Linux implementation.

**Comment by goelvidhi** [comment]
@lisongxu this is exactly what we do for Apple's CUBIC as well.

I am open to adding `origin_point` if there is no objection about additional complexity.

**Comment by larseggert** [comment]
I'd say let's add it. Anyone know what Windows is doing? Is Praveen on GitHub?

**Comment by goelvidhi** [comment]
I want to add a clarification point to my previous comment about the below code. We do this only when we enter CA without any loss i.e. when cwnd > ssthresh.

```
if (cwnd < W_max)
{
    K = cubic_root((W_max - cwnd)/C)
    origin_point = W_max
}
else
{
    K = 0
    origin_point = cwnd
}
```

Note that at the beginning of CA, we should only do the below, as we want to start with W_max and not current value of cwnd. Also, as W_max will be greater than cwnd at the start of CA, the else condition doesn't apply.
```
K = cubic_root((W_max - cwnd)/C)
origin_point = W_max
```

So, I think we can leave Eq. 1 as is.

**Comment by lisongxu** [comment]
There is another important difference between this RFC and Linux TCP in fast recovery. RFC assumes that cwnd is set to W_max * beta_cubic in fast recovery and remains as W_max * beta_cubic at the beginning of a congestion avoidance stage. However, the behavior of Linux TCP in/around fast recovery is complicated, such as adjusting cwnd based on the number of packets in flight, and adjusting cwnd in case of undo. As a result, at the beginning of a congestion avoidance stage, cwnd may or may not be W_max * beta_cubic, and sometimes may be even higher than W_max. 

I guess this RFC does not need to follow the fast recovery of Linux TCP, but it is safer to add that else condition. 

Thanks

**Comment by lisongxu** [comment]
Yes,  @goelvidhi   you are right that we do this only when cwnd > ssthresh

**Comment by lisongxu** [comment]
> @lisongxu this is exactly what we do for Apple's CUBIC as well.
> 
> I am open to adding `origin_point` if there is no objection about additional complexity.

Thanks, @goelvidhi for confirming Apple's implementation!

**Comment by maolson-msft** [comment]
Rather than patching the K computation, why not set (after applying the fast convergence logic to W_max)
CWnd = BETA * W_max

rather than
CWnd = BETA * CWnd

when we reduce the window? I.e., wrap the fast-convergence reduction into both W_max and the CWnd. That seems more harmonious with the fast convergence algorithm, and at least for me, it's easier to reason about its effect.

**Comment by lisongxu** [comment]
@maolson-msft Yes, that is another possible design choice. The main reason to update the K equation is to revise the RFC to be consistent with the Linux cubic implementation and the original paper.  Thanks

**Comment by goelvidhi** [comment]
@maolson-msft that would also require updating `ssthresh`, otherwise we will end up in slow start. I think the current approach is fine.

**Comment by goelvidhi** [comment]
@lisongxu I updated the Eq. 2 with an else condition. Also, added some text for how cwnd can be set. Could you please review https://github.com/NTAP/rfc8312bis/pull/3?

**Comment by lisongxu** [comment]
If we do not use variable origin_point, then it is possible that W_cubic(t) may be lower than the current cwnd.  In this case, I would suggest changing Equation (1) as follows, which also contains the bug fix. 
```
    W_cubic(t) = C*(t-K)^3 + W_max
    if (W_cubic(t) < cwnd)                      // lower bound
        W_cubic(t)  =  cwnd
    else if (W_cubic(t) > 2* cwnd)              // upper bound
        W_cubic(t)  =  2 * cwnd
where cwnd is the current congestion window size.
```

Below is a slightly revised Equation (2)
```
   if (cwnd_0 < W_max) {
        K = cubic_root(W_max - cwnd_0) / C             
    } else {
        K = 0
    }
where cwnd_0 is the congestion window at the beginning of a congestion avoidance stage, is calculated using beta_cubic in {{mult-dec}}, although implementations can further adjust the congestion window size based on other fast recovery mechanisms. We discuss how we set beta_cubic in {{mult-dec}} and how we set C in {{discussion}}.
```

**Comment by larseggert** [comment]
Why aren't we using origin_point?

**Comment by goelvidhi** [comment]
As we initially thought origin_point was needed only when cwnd > ssthresh without loss.

But @lisongxu mentioned, cwnd could become greater than W_max at the start of CA (after a congestion event). I want to understand in what case would it become greater. 
1. Using bytes in flight shouldn't set cwnd greater than W_max
2. For any undo, W_max should also be undo'ed.

Anything else?

**Comment by goelvidhi** [comment]
> If we do not use variable origin_point, then it is possible that W_cubic(t) may be lower than the current cwnd. In this case, I would suggest changing Equation (1) as follows, which also contains the bug fix.
> 
> ```
>     W_cubic(t) = C*(t-K)^3 + W_max
>     if (W_cubic(t) < cwnd)                      // lower bound
>         W_cubic(t)  =  cwnd
>     else if (W_cubic(t) > 2* cwnd)              // upper bound
>         W_cubic(t)  =  2 * cwnd
> where cwnd is the current congestion window size.
> ```
> 
> Below is a slightly revised Equation (2)
> 
> ```
>    if (cwnd_0 < W_max) {
>         K = cubic_root(W_max - cwnd_0) / C             
>     } else {
>         K = 0
>     }
> where cwnd_0 is the congestion window at the beginning of a congestion avoidance stage, is calculated using beta_cubic in {{mult-dec}}, although implementations can further adjust the congestion window size based on other fast recovery mechanisms. We discuss how we set beta_cubic in {{mult-dec}} and how we set C in {{discussion}}.
> ```

If I use cwnd_0 (which is beta_cubic * W_max) , then I don't need to else condition, right?

**Comment by lisongxu** [comment]
How about revising Section 4.1 as follows?

CUBIC uses the following window increase function:
```
       W_cubic(t) = C*(t-K)^3 + W_max (Eq. 1)
```
   where C is a constant fixed to determine the aggressiveness of window increase in high BDP networks and is discussed in Section 5, t is the elapsed time from the beginning of the current congestion avoidance stage, and K is the time period that the above function takes to increase the current window size to W_max if there are no further congestion events and is calculated using the following equation:
```
       K = cubic_root( (W_max-cwnd_0) /C)  (Eq. 2)
```
   where cwnd_0 is the congestion window at the beginning of the current congestion avoidance stage. In special cases, if cwnd_0 is greater than W_max, K is set to 0.

   Upon receiving an ACK during congestion avoidance, CUBIC computes the target congestion window size after the next RTT as follows, where RTT is the weighted average RTT calculated by Standard TCP.
```
        target = W_Cubic(t + RTT)      // cwnd after a RTT
        if (target < cwnd)             // lower bound
            target = cwnd
        else if (target > 2*cwnd)      // upper bound
            target = 2 * cwnd
```

**Comment by goelvidhi** [comment]
this looks good to me. I will update the PR with some minor text edits.

**Comment by goelvidhi** [comment]
Thinking a bit more about it, I think cwnd_0 looks a bit confusing. Also, as we are adding text for special case (if cwnd > W_max),  and later to ensure target is within bounds, I think we should just call it `cwnd` and describe it as you did `where cwnd is the congestion window at the beginning of the current congestion avoidance stage`

**Comment by lisongxu** [comment]
@goelvidhi fine with me. Thanks.

**Comment by rscheff** [comment]
> We calculate K only once at the beginning of a congestion avoidance stage.

While this is a correct statement, there are many more events that signify the beginning of the CA stage than just coming out from slow-start. In the cubic implementaiton in FreeBSD, the recalculation of K was missed in most of these instances (after idle, RTO rewind, loss recovery*, ecn recovery*). 

As a note from an implementer, mentioning these other cases that signify the beginning of the congestion avoidance stage may avoid issues where someone only thinks of the textbook example when cwnd > ssthresh as the start of CA...


(*) strictly speaking, K should be recalculated once the loss/ecn recovery has finished; FreeBSD takes a shortcut here and calculates K when entering recovery rather after leaving recovery.

**Comment by rscheff** [comment]
> Thinking a bit more about it, I think cwnd_0 looks a bit confusing. Also, as we are adding text for special case (if cwnd > W_max), and later to ensure target is within bounds, I think we should just call it `cwnd` and describe it as you did `where cwnd is the congestion window at the beginning of the current congestion avoidance stage`

Actually, reading "cwnd" in the formula by itself is more confusing to me, than referecing this by any other name; cwnd is the "current" cwnd on a casual glance; if it is NOT the current cwnd, but some state which has to be kept, use a differnt variable name in the formulas to make this clear (cwnd_0 or cwnd_base would be fine by me).

**Comment by goelvidhi** [comment]
> (*) strictly speaking, K should be recalculated once the loss/ecn recovery has finished; FreeBSD takes a shortcut here and calculates K when entering recovery rather after leaving recovery.

I don't think there is any mention of K being calculated only when cwnd > ssthresh. K is always recalculated whenever there is a congestion event.



> Actually, reading "cwnd" in the formula by itself is more confusing to me, than referecing this by any other name; cwnd is the "current" cwnd on a casual glance; if it is NOT the current cwnd, but some state which has to be kept, use a differnt variable name in the formulas to make this clear (cwnd_0 or cwnd_base would be fine by me).

'cwnd' is current congestion window in that formula. As @lisongxu noted, `In special cases, if cwnd is greater than W_max, K is set to 0.`, this additional statement will clarify what one needs to do if it is greater than W_max.

**Comment by sangtaeha** [comment]
@goelvidhi @rscheff  Using 'cwnd' looks okay to me, and an implementer can use any variable of her choice to reference or store this value, e.g., 'origin_point' or 'cwnd_0.' Thanks!

**Comment by goelvidhi** [comment]
Thanks @sangtaeha. Could you please review https://github.com/NTAP/rfc8312bis/pull/3? Thanks.

**Comment by rscheff** [comment]
Sorry, I probably have missed something - K is recalculated at the beginning of a congestion avoidance phase, with the then-current cwnd. What would be the reason to store that value for later use (or why was it referred to as 'cwnd_0' or 'origin_point'? What uses are for that cwnd in the past in some implementations. (Still suffering from virtual jetlag, sorry).

**Comment by lisongxu** [comment]
@rscheff Thank you. In normal cases, we do not need to store that value (cwnd_0, or origin_point) for later use.
