### ISSUE TITLE
Highlight difference to paper

### ISSUE THREAD

**Issue by mirjak** [NTAP/rfc8312bis#10]
Would be nice to highlight what has changed from the original paper as that paper is still a good source to start with and understand cubic.

**Comment by sangtaeha** [comment]
RFC 8312 was close to the original paper, and this version clarifies a few implementation details. This is more like we explain the difference between RFC 8312 and a new version. @larseggert and @lisongxu If you want to include this, I can help. We may have to use a separate section for this information?

**Comment by larseggert** [comment]
Yes, a separate section (or an appendix) makes sense. I think discussing both the changes from the paper to RFC8312 and from RFC8312 to this document (RFC8312bis) would make sense?

**Comment by mirjak** [comment]
Actually the main reason why I checked the paper is because it has the pseudo code. I also look at the linux implementation but that's much harder to understand, especially if your implementation doesn't need the same optimisations. Might be also worth discussing in an appendix.

**Comment by sangtaeha** [comment]
@mirjak I agree.

**Comment by lisongxu** [comment]
Thanks, @sangtaeha

**Comment by larseggert** [comment]
@sangtaeha would you start a PR for this?

**Comment by sangtaeha** [comment]
@larseggert Yes, let me get back to you on this.

**Comment by sangtaeha** [comment]
@mirjak @lisongxu @larseggert There are a few differences between the original paper and RFC8312. The major difference is the first bullet. The second bullet of each version might be trivial and can be removed. Any feedback on the following? After that, I will submit a PR.

## RFC 8312

- It changed the definition of beta_cubic constant and thus updated the pseudocode of CUBIC accordingly. For example, beta_cubic in the original paper was the window decrease constant while RFC8312 changed it to CUBIC multiplication decrease factor. With this change, the current congestion window size after a loss event is beta_cubic * W_max while it was
(1-beta_cubic) * W_max in the original paper.
- It included the discussion on safety features of CUBIC, such as CUBIC's fairness in small and high bandwidth-delay product (BDP) networks and the recommended CUBIC constant C.

## Original paper

- The original paper included the pseudocode of CUBIC implementation using Linux's pluggable congestion control framework, which excludes system-specific optimizations. The simplified pseudocode might be a good source to start with and understand CUBIC.
- It also includes experimental results showing its performance and fairness.

**Comment by lisongxu** [comment]
Thanks, @sangtaeha

**Comment by lisongxu** [comment]
There is one more difference: W_last_max in the paper and in the Linux code is called W_max in the RFC. Thanks

**Comment by sangtaeha** [comment]
Good point. I add that. Thanks, @lisongxu

**Comment by goelvidhi** [comment]
> There is one more difference: W_last_max in the paper and in the Linux code is called W_max in the RFC. Thanks

I think the paper uses W_max in the text but only uses W_last_max in the code.

Other differences that I see based on the recent changes:
1. K formula has changed in the RFC, to cbrt ((W_max - cwnd)/C) whereas in the paper it is cbrt((W_max * Beta)/C) where Beta = 1-cubic_beta
2. TCP friendly window is called W_est in the RFC whereas it is W_tcp in the paper (subtle difference). Also, we added a note to change alpha_aimd to 1 when W_est > W_max
3. Fast Convergence section - Although Section 3.7 describes the fast convergence using W_max and W_last_max (which is same as the RFC), the corresponding pseudocode in Algorithm 1 only uses W_last_max (as W_max) and it seems a bit incorrect. Not sure what we add regarding this.

**Comment by sangtaeha** [comment]
Thanks, @goelvidhi. Yes, we may have more changes as well. I will incorporate them into the list.

**Comment by larseggert** [comment]
Should we also discuss the improvements taken from the NSDI paper, and cite that?

**Comment by sangtaeha** [comment]
@larseggert Yes, we can include those in the list of changes since RFC 8312.

**Comment by sangtaeha** [comment]
@goelvidhi Yes, the Fast Convergence pseudocode was wrong while the explanation was correct. That was the issue of using w_max and w_last_max in different places. We may not add this issue but we should add the changes in the K formula and TCP friendly region which now emulates TCP throughput using segments or bytes received instead of time t.

**Comment by goelvidhi** [comment]
Sounds good.
