### ISSUE TITLE
W_max

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#135]
From @markkukojo in #85:
> Moreover, I didn't notice it earlier but this also means that setting W_max should be different if the sender is in slow start when a pkt loss (congestion) is detected and cwnd is reduced.
If CUBIC sets W_max to size of cwnd just before cwnd was reduced when in slow start alike when in CA, it results not only starting the first CA epoch after fast recovery with an overaggressive cwnd (using MD=0.7) above the actual saturation point but also starting the subsequent CA with the concave phase and continuing with the concave phase until cwnd reaches value that is double the saturation point. This makes CUBIC (when not in Reno-friendly region) much more aggressive than intended because it operates in the concave phase even though the cwnd size actually already exceeds the previous saturation point (which in the above example is 200 not 400).
>
>IMO this issue of which MD factor to use when in slow start is not resolved. Please also add the problem with setting W_max when in slow start to the set of open issues.

**Comment by larseggert** [comment]
Any takers for this one?

**Comment by nsdyoshi** [comment]
I think this is an interesting discussion point. My tentative thoughts on this are:
* if hystart++ is used, the chances to get losses during slowstart will be reduced
* if a certain pacing is used, the burstness in the first CA epoch is reduced which might help finding saturation point without large losses
* using MD=0.5 upon the loss after SS may be one idea especially when the options above are not used.
* But, I'm still thinking how bad concave growth in the first CA is. if cwnd at loss during SS is too far from the actual saturation point, both reno and cubic will hit saturation point is quickly in the first CA. there might not be big differences. if the cwnd at loss during SS is close to the actual saturation point, cubic gain more bandwidth than reno especially under long RTTs, but this might be what cubic is.

**Comment by lisongxu** [comment]
I will work on this issue. Thanks

**Comment by lisongxu** [comment]
Quick update: still working on it, try to find a reasonable solution for both #135 and #85.  Thanks

**Comment by lisongxu** [comment]
Update: 

Thank you all, @markkukojo  @nsdyoshi, for your comments and suggestions! 

We agree that both MD and Wmax may be adjusted differently for slow start and congestion avoidance. As this could be a major change to CUBIC, we (thanks, @sangtaeha) plan to comprehensively test and evaluate this change in various network environments, which will take some time.

**Comment by larseggert** [comment]
I will hence close this.
