### ISSUE TITLE
Clarification about cwnd and flight size when referring to RFC 7661

### ISSUE THREAD

**Issue by goelvidhi** [NTAP/rfc8312bis#143]
@nsdyoshi said,
 I just have one more comment on the draft.
In RFC5681, it mentions in Section 3:
''
   Implementation Note: An easy mistake to make is to simply use cwnd,
   rather than FlightSize, which in some implementations may
   incidentally increase well beyond rwnd.
"

while this draft mentions in Section 4.6:
"
   To avoid suboptimal performance with such applications,
   the mechanisms described in [[RFC7661](https://datatracker.ietf.org/doc/html/rfc7661)] can be used to mitigate this
   issue as it would allow using a value between _cwnd_ and
   _flight_size_ to calculate the new _ssthresh_ in Figure 5. 
"
So, it seems one PS doc mentions not to use cwnd, while another PS doc mentions using cwnd is fine (with RFC7661).

I am not sure which can cause this situation yet, but in any case, does this mean there is no concern on 
"some implementations may incidentally increase well beyond rwnd" in cubic?
Is this because this is an old implementation bug or are there other reasons?
I am wondering if we might want some clarification on this point.
 
Also, I am wondering if we might want to use "MAY be used" here instead of "can be used"

**Comment by larseggert** [comment]
> So, it seems one PS doc mentions not to use cwnd, while another PS doc mentions using cwnd is fine (with RFC7661).

We could point out that disagreement in our text, and use it to argue for our preference.

> Also, I am wondering if we might want to use "MAY be used" here instead of "can be used"

That should be fine.

**Comment by yuchungcheng** [comment]
I also agree the writing can be more precise on computing ssthresh, in particular the "value between" wording is too arbitrary.

Will this look more clear?
"To avoid suboptimal performance with such applications, if RFC7661 is implemented, ssthresh in Figure 5 MAY be based on cwnd instead of flight_size."

**Comment by goelvidhi** [comment]
> I also agree the writing can be more precise on computing ssthresh, in particular the "value between" wording is too arbitrary.
> 
> Will this look more clear? "To avoid suboptimal performance with such applications, if RFC7661 is implemented, ssthresh in Figure 5 MAY be based on cwnd instead of flight_size."

It may still be not enough and we may need to explain why RFC 7661 is acceptable. I will propose something in a PR and we can discuss on that.

**Comment by nsdyoshi** [comment]
+1 for adding explanations why we can override the statement in RFC5681.

**Comment by goelvidhi** [comment]
Created a PR with some additional text. @yuchungcheng, I wasn't able to add you as a reviewer. Could you take a look at the PR here, https://github.com/NTAP/rfc8312bis/pull/144
