### ISSUE TITLE
Odd shrinking formulae

### ISSUE THREAD

**Issue by martinthomson** [NTAP/rfc8312bis#153]
![image](https://user-images.githubusercontent.com/67641/189276965-f5171326-f602-453c-8935-fff63d1dd377.png)

Any idea why the first is so much smaller than the second?

**Comment by larseggert** [comment]
I don't know.

**Comment by nealcardwell** [comment]
Is it possible that it's due to the trailing double-backslashes \\ at the end of the line causing that line to be small?

  α_{cubic} = 3 * \frac{1 - β_{cubic}}{1 + β_{cubic}} \\

**Comment by larseggert** [comment]
That was is. Thanks @nealcardwell!
