### ISSUE TITLE
Add Injong as co-author

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#16]
Welcome @injongrhee! Please prepare a pull request to add yourself to the authors' block and `CODEOWNERS`.

**Comment by larseggert** [comment]
Merged, thanks! @Injongrhee could you please accept the invite to join the repo, so we can assign you reviews, etc.?

**Comment by sangtaeha** [comment]
@larseggert, @Injongrhee could not find that invitation. Can you send an invite to him again?

**Comment by larseggert** [comment]
Done. He should have gotten an email and see a notification in GitHub.
