### ISSUE TITLE
"TCP-Friendly" is a bit misleading

### ISSUE THREAD

**Issue by martinthomson** [NTAP/rfc8312bis#38]
Given that a lot of TCP deployments use Cubic, I think that the intent here is to be friendly to Reno instead.  As the text establishes, it is AIMD(1, 0.5) that this wants to be sensitive to.

It might have made sense to talk about TCP when Cubic wasn't widely deployed, but now it is just confusing.

**Comment by larseggert** [comment]
Agreed. We need to do a larger rewrite of much of the beginning of the document, which was historically correct but is now outdated, given that all stacks default to CUBIC.

**Comment by lisongxu** [comment]
I can also help to revise the text later next week, is it ok? Thanks, Lars
