### ISSUE TITLE
Change introductory text to reflect deployment experience

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#39]
The abstract, introduction and other text throughout the document need to be updated to reflect the significantly broader deployment experience CUBIC has seen since RFC8312 was published. At that time, it had been the default for Linux for years, but since then, it's also been the default for Windows and Apple stacks.

**Comment by lisongxu** [comment]
Thanks, Lars. I can help to revise the text later next week, is it ok?

**Comment by goelvidhi** [comment]
@lisongxu I just wanted to check with you if you'd have time to work on it? :-)

**Comment by lisongxu** [comment]
Hi Vidhi,

Thanks for checking with me. Really sorry that I am much busier than what I expected due to multiple back to back deadlines. It looks like that I will have some time to work on it next week after Monday (my last deadline this month :-) ).

Thanks
Lisong

________________________________

**Comment by larseggert** [comment]
Mon, Feb 22 is the cutoff date for i-D submissions for IETF-110. If we're not ready to submit by then, we'll have to wait until mid-March. Which isn't a huge issue, but since we're going to ask for WG adoption, it would be nice to have a more up-to-date I-D to discuss.

**Comment by lisongxu** [comment]
I see. I will try my best. Thanks
Lisong

________________________________
