### ISSUE TITLE
CUBIC for QUIC

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#45]
Since most of the new implementations for CUBIC will be in the context of QUIC stacks (as opposed to TCP stacks), it would be useful to add a section or an appendix on how one would do that. For example, it might make sense to describe how CUBIC would be integrated into an implementation that followed the [QUIC -recovery](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html) draft.

**Comment by junhochoi** [comment]
quiche provides cubic as a default congestion control: https://github.com/cloudflare/quiche/blob/master/src/recovery/cubic.rs
This is rather a as-is implemetation of RFC8312 and HyStart++ draft. I am working on updating this following changes in this draft, such as https://github.com/cloudflare/quiche/pull/861

For implementor, most things are same, but QUIC defines (and I think most of TCP stack other than Linux?) congestion control window as a unit of bytes but the RFC8312 and this drafts defined cwnd as a unit of segment, so need to be careful when you calculate K and W_cubic.

**Comment by larseggert** [comment]
Would you be interested in submitting a PR that would summarize these changes? Are there other QUIC stacks that are implementing CUBIC from scratch? I think picoquic did?

**Comment by goelvidhi** [comment]
IMO, it is quite straight forward to implement CUBIC using the pseudocode in [QUIC Recovery](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html) draft and adding the CUBIC pieces to the functions defined in it.

CUBIC draft defines congestion window in segments which most implementors simply convert to bytes by multiplying by MSS.

**Comment by huitema** [comment]
My notes on implementing Cubic for QUIC are at https://huitema.wordpress.com/2019/11/11/implementing-cubic-congestion-control-in-quic/. I already provided feedback to the "bis" RFC. Yes, porting Cubic to QUIC is fairly straightforward. My main implementation issue was understanding the dimensions of each formula.

Two important points from the bis draft:

1. Forget about the TCP friendly formula. It does not work well, because RTT jitter will translate in CWIN swings. It is much simpler to just run the RENO algorithm in parallel and set the CWIN to max(Reno, Cubic)
2. You really want to implement the recovery from spurious losses discussed in the bis draft. I think this is actually the reason for the drop in perf in face of reordering mentioned in the EPIC paper "Making QUIC Quicker With QUIC Offload". Not the CPU cost of reordering.

**Comment by goelvidhi** [comment]
Thank you @huitema for the issues you had filed earlier. All of these have been addressed. 

> My notes on implementing Cubic for QUIC are at https://huitema.wordpress.com/2019/11/11/implementing-cubic-congestion-control-in-quic/. I already provided feedback to the "bis" RFC. Yes, porting Cubic to QUIC is fairly straightforward. My main implementation issue was understanding the dimensions of each formula.

This is fixed with the new section [Definitions](https://tools.ietf.org/html/draft-eggert-tcpm-rfc8312bis-02#section-4.1)
> 
> Two important points from the bis draft:
> 
> 1. Forget about the TCP friendly formula. It does not work well, because RTT jitter will translate in CWIN swings. It is much simpler to just run the RENO algorithm in parallel and set the CWIN to max(Reno, Cubic)

AIMD friendly formula now is based on RENO - [Section 4.3](https://tools.ietf.org/html/draft-eggert-tcpm-rfc8312bis-02#section-4.3)

> 2. You really want to implement the recovery from spurious losses discussed in the bis draft. I think this is actually the reason for the drop in perf in face of reordering mentioned in the EPIC paper "Making QUIC Quicker With QUIC Offload". Not the CPU cost of reordering.

IIRC, this was the issue you had filed and we add a new section [Spurious Congestion Events](https://tools.ietf.org/html/draft-eggert-tcpm-rfc8312bis-02#section-4.9)

**Comment by huitema** [comment]
@goelvidhi yes, I appreciate that the issues have been addressed in the new draft. This is good. @larseggert was asking whether there was something specific to say about Cubic for QUIC. The main remaining issue is about translating the windows counts from "packets" to "bytes". When I ported Cubic to QUIC, I spent some time doing that. I first rewrote the Cubic formula:
```
                                             3
                      W     (t) = C * (t - K)  + W
                       cubic                      max
```
In a "neutral" way:
```
                                                    3
                                        /    /t - K\     \
                      W     (t) = W  * (C' *( ----- )  + 1)
                       cubic       max  \    \  K  /     /
```
This rewrite helped me understand what was going on. We have a windows size coefficient, `Wmax`, expressed in the same unit as CWIN; a coefficient C' that is a pure scalar and defines the `aggressiveness` of the implementation; and a cubic curve that is a function of `(t-K)/K`. The same rewrite helps understand the coefficient C -- or C' in the new notation.
```
                            C     3
                      C' = --- * K
                            W
                             max
```
Which reduces to:
```
                                   / W    - W    \
                            C     /   max    start\     
                      C' = --- * ( ----------------)
                            W     \       C       /
                             max

                             / W    - W    \
                            /   max    start\     
                      C' = ( ----------------)
                            \       W       /
                             \       max   /
```
In most cases, when `sstresh` is larger than 2 packets, this reduces further:
```
                      W      = β W
                       start      max

                      C' = (1 - β)

                                                         3
                                        /         /t - K\     \
                      W     (t) = W  * ((1 - β) *( ----- )  + 1)
                       cubic       max  \         \  K  /     /
```
The formula does not depend on the unit of W, packet or bytes. The coefficient C disappears, but of course it is key in computing the pseudo-period `K` of the cubic curve.

**Comment by junhochoi** [comment]
@huitema re: Spurious Congestion Events. What's your algorithm to detect a spurious retransmissions in QUIC? In the draft DSACK, F-RTO and Eifel is listed but I think none of them is directly applicable to QUIC recovery.

I tried to do similar thing in Reno before motivated by your work: https://github.com/cloudflare/quiche/pull/308
It's still Reno but the idea is same. I used the condition "<end of recovery> - <start of recovery> < 2 x minRTT" here but maybe it's too simple.

**Comment by huitema** [comment]
Picoquic detects spurious retransmission event by keeping a list of packets that were recently retransmitted. The logic is:

1. when the packet is first sent, keep a copy in the list of packets not-yet-acknowledged.
2. when an ACK is received, remove the acked packets from the not-yet-acknowledged list. Mark the frames inside the packet as processed (e.g. stream frames so the corresponding stream data is never repeated; ack frames so ack ranges are marked as already known by the peer). Signal that data was acked to CC engine. (but see also step 4)
3. when running loss detection, if a packet is deemed lost, mark frames for retransmission as appropriate; move the packet copy from the not-yet-acknowledged list to the "retransmitted" list. Signal that packet was lost to CC engine.
4. when an ACK is received, check whether some of the acked packets are in the retransmitted list. If so, signal spurious retransmission to the CC engine. Also, mark the frames inside the packet as processed, etc.

**Comment by goelvidhi** [comment]
>                                                          3
>                                         /         /t - K\     \
>                       W     (t) = W  * ((1 - β) *( ----- )  + 1)
>                        cubic       max  \         \  K  /     /
> ```
> 
> The formula does not depend on the unit of W, packet or bytes. The coefficient C disappears, but of course it is key in computing the pseudo-period `K` of the cubic curve.

@huitema you arrived at this formula by substitution but I don't see how is it better than 
[Figure 1](https://www.ietf.org/archive/id/draft-eggert-tcpm-rfc8312bis-02.html#figure-1).

For folks who use bytes instead of segments for congestion window, they would still need to divide by mss in [Figure 2](https://www.ietf.org/archive/id/draft-eggert-tcpm-rfc8312bis-02.html#figure-2) to compute K.

I think the units that we have added in the new draft will help folks in deciding when to divide/multiply by segment size.

**Comment by junhochoi** [comment]
@huitema thanks for how to detect spurious retransmission! I will take a look if this is applicable to quiche.

**Comment by junhochoi** [comment]
Additionally,
- integer vs floating point arithmetic: most of quic implementaion is userland, easier to use floating point arithmetic for various calculation. But for high performance it'll be better to make it integer ops only. 
- I wrote a blog post last year when I implemented cubic in quiche: https://blog.cloudflare.com/cubic-and-hystart-support-in-quiche/
- [quicly](https://github.com/h2o/quicly/blob/master/lib/cc-cubic.c) and [msquic](https://github.com/microsoft/msquic/blob/main/src/core/congestion_control.c) has CUBIC too.

**Comment by huitema** [comment]
@goelvidhi I started this rewriting of formulas in an attempt to understand how the coefficients C and β affect the behavior of Cubic. The rewritten formula shows that the key coefficients are really:

* An amplitude coefficient, β. Changing the value of β from for example 3/4th to 7/8th reduces the amplitude of the variations, both before the inflection point and after it.
* A pseudo-period K, which sets the time between the beginning of the epoch and the inflection point. Shorter values of K will cause Cubic to adapt and probe faster, and vice versa.

The rewriting also shows the problem with the original formula. It results from experiments and adaptations, but it is quite hard to understand how K will vary with bandwidth, latency, and the value of C. A stated design goal of Cubic is to share the bottleneck bandwidth fairly between competing connections experiencing different RTT. I would expect that the computation of the pseudo-period result such design goals, from design principles, but the formulas are very hard to derive. We end up with empirical tuning, such as "we tried C=0.0004 and it works well". I don't find that very satisfactory.

**Comment by goelvidhi** [comment]
Quoting from the draft, 

> Two CUBIC flows with different RTTs have a throughput ratio that is linearly proportional to the inverse of their RTT ratio, where the throughput of a flow is approximately the size of its congestion window divided by its RTT.

> Specifically, CUBIC maintains a window increase rate independent of RTTs outside of the AIMD-friendly region, and thus flows with different RTTs have similar congestion window sizes under steady state when they operate outside the AIMD-friendly region.

The bandwidth will be shared fairly in the sense that the congestion window will grow similarly but the throughput is still inversely proportional to the RTT.

**Comment by huitema** [comment]
I understand that each loss event triggers a computation of the formula, and that at equilibrium the average WMAX is a function of packet loss rate. So, yes, in that sense there is fairness. On the other hand, that property is also true for new Reno. There are two problems on New Reno with high latency links: the dependency on loss rate, which limits the size of the window; and the dependency on RTT, which privilege short RTT. WMAX in Cubic converges at a higher value than ssthresh in Reno, which is better for high latency links. But we still have the issue of RTT unfairness.

**Comment by goelvidhi** [comment]
If by RTT unfairness, you mean throughput inversely proportional to RTT, then yes, that is a design limitation of CUBIC. I am not sure what update you are expecting/suggesting.:-)

**Comment by huitema** [comment]
Sorry, not expecting any change at this point. I should write all that in a paper.

**Comment by larseggert** [comment]
So does the current text address all issues raised by @junhochoi and @huitema? If yes, I will close this.

**Comment by larseggert** [comment]
And FYI, I am planning to submit a new revision before the TCPM meeting, to roll in all the changes since -01. If we need additional changes that are easy to make to address this issue, it would be good to get them in soon.

**Comment by junhochoi** [comment]
My question is answered in the different ticket so it's ok. I think the goal of this issue is to add some text around QUIC implementation?

**Comment by goelvidhi** [comment]
As I mentioned earlier, with the current CUBIC draft, it is quite straight forward to adopt it for QUIC by plugging into the pseudo code in QUIC recovery draft. @junhochoi is there anything specific that seemed tricky to implement Cubic for QUIC?

**Comment by junhochoi** [comment]
@goelvidhi I am still working on updating quiche CUBIC according to this draft. I may find more but I commented most of them in this ticket already.

Also it's one of my comment but again, in "Spurious Congestion Events" section most of algorithms detecting spurious retransmission is not directly applicable in QUIC and QUIC recovery draft doesn't mention about it, so you need to implement your own.

**Comment by goelvidhi** [comment]
Yes, I had discussed this briefly in QUIC WG and I was pointed to the below text. I know that this text doesn't talk about how the congestion controller should react to it but once a spurious loss is detected (some TCP RFCs talk about how to detect it), one can follow the CUBIC Section for Spurious Congestion events.

> Spuriously declaring packets as lost leads to unnecessary retransmissions and may result in degraded performance due to the actions of the congestion controller upon detecting loss. Implementations can detect spurious retransmissions and increase the reordering threshold in packets or time to reduce future spurious retransmissions and loss events.

**Comment by WesleyRosenblum** [comment]
One thing I noticed is that if you use min RTT instead of smoothed RTT ([as Linux TCP Cubic does](https://github.com/torvalds/linux/blob/05a59d79793d482f628a31753c671f2e92178a21/net/ipv4/tcp_cubic.c#L266)), you can potentially end up with a divide by zero in the `w_est` calculation. This is because the [QUIC Recovery pseudocode](https://tools.ietf.org/id/draft-ietf-quic-recovery-34.html#name-initialization) initializes the min_rtt to 0. An endpoint can enter congestion avoidance without receiving any acks for any ack-eliciting packets (only non-ack eliciting packets), and thus min_rtt would still be zero at the time `w_est` is calculated. This can be addressed by initializing `min_rtt` to `kInitialRtt` instead of zero.

Though, now that `w_est` no longer incorporates `t/RTT` this shouldn't be an issue.

**Comment by larseggert** [comment]
@WesleyRosenblum is this something that should be fixed in the QUIC -recovery document? If yes, please file an issue at https://github.com/quicwg/base-drafts/issues

**Comment by WesleyRosenblum** [comment]
Thanks, I've opened an issue the Quic WG: https://github.com/quicwg/base-drafts/issues/4833

**Comment by goelvidhi** [comment]
As of now, there is nothing to do here. I am closing this issue.
