### ISSUE TITLE
In PDF, alpha/beta looks broken

### ISSUE THREAD

**Issue by junhochoi** [NTAP/rfc8312bis#46]
In a converted PDF, it looks like alpha -> Î± and beta -> Î²

For example,
```
α_{aimd} = 3 * \frac{1 - β_{cubic}}{1 + β_{cubic}}
```

looks like following:

<img width="745" alt="Screen Shot 2021-02-23 at 6 02 39 PM" src="https://user-images.githubusercontent.com/1229714/108934304-8a2a3980-7601-11eb-96cb-dc0fa1a7855a.png">

**Comment by junhochoi** [comment]
others (txt, html) looks fine.

**Comment by larseggert** [comment]
Which PDF are you looking at?

**Comment by junhochoi** [comment]
I am looking https://tools.ietf.org/pdf/draft-eggert-tcpm-rfc8312bis-02.txt
(wow it's PDF but has .txt extension)

**Comment by larseggert** [comment]
Thanks, I filed https://trac.tools.ietf.org/tools/ietfdb/ticket/3191

**Comment by larseggert** [comment]
Closing this, since it's an issue with tools.ietf.org and not this document.
