### ISSUE TITLE
List of variables and constants

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#5]
It would be useful to add a consolidated list of all constants and variables with their units and a brief description.

**Comment by goelvidhi** [comment]
I can help with this

**Comment by lisongxu** [comment]
Thank you, Vidhi!

**Comment by goelvidhi** [comment]
@lisongxu  @sangtaeha could you please review https://github.com/NTAP/rfc8312bis/pull/12?

**Comment by lisongxu** [comment]
the unit of C should be MSS / S^3 ? Thanks

**Comment by goelvidhi** [comment]
Is Segment / S^3 ok? (as I am calling the units of cwnd, W_max as segments)

**Comment by lisongxu** [comment]
Yes, thanks.

**Comment by goelvidhi** [comment]
done. please review.
