### ISSUE TITLE
ssthresh and cwnd_start should not exceed Beta_cubic * congestion window at loss

### ISSUE THREAD

**Issue by goelvidhi** [NTAP/rfc8312bis#53]
Lisong's mentioned this in an off-line discussion,

Below I will use X to refer to (beta * cwnd right before the congestion event).

An implementation of CUBIC can choose different ways to adjust the cwnd during the fast recovery and timeout.

But after the fast recovery/ECN, it should set cwnd (i.e., cwnd_start) and ssthresh to X. This is because all the parameters (such as C, alpha, and beta) of CUBIC are chosen based on this assumption. If an implementation chooses its own ssthresh and own cwnd_start, then the performance of such an implementation will be very different from what we expected. 

I understand and agree with your motivation to be more flexible (as CUBIC may be implemented for various purposes, TCP, UDP, media streaming as RC 7661, QUIC, .... ). Therefore, I would suggest that an implementation SHOULD set ssthresh and cwnd_start to X, and it MAY set them to a value lower than X as the cost of lower performance. But it MUST NOT set them to a value higher than X.

**Comment by larseggert** [comment]
I think #54 is supposed to address this? Marking it as such.
