### ISSUE TITLE
Update the definition of W_max to include fast convergence scenario

### ISSUE THREAD

**Issue by goelvidhi** [NTAP/rfc8312bis#55]
Copying some suggestions from Lisong here,

change  "wmax: size of cwnd just before cwnd was reduced in the last congestion event".    
to  "wmax: size of cwnd just before cwnd was reduced in the last congestion event when fast convergence is disabled" 
or  "wmax: cwnd (without fast convergence) or reduced cwnd (with fast convergence) just before cwnd was reduced in the last congestion event" ?

**Comment by larseggert** [comment]
Do we still want to make this change?

**Comment by lisongxu** [comment]
Yes, I can make this change in one or two days. Thanks
Lisong

________________________________

**Comment by goelvidhi** [comment]
Thanks Lisong. Will assign the issue to you.
(Sorry I was slow in responding)

**Comment by lisongxu** [comment]
No problem. Thanks
Lisong

________________________________

**Comment by sangtaeha** [comment]
@lisongxu Yes, this is more precise. "wmax: size of cwnd just before cwnd was reduced in the last congestion event when fast convergence is disabled"

**Comment by lisongxu** [comment]
Thanks Sangtae! Any suggestions on how to clearly describe wmax when fast convergence is enabled?

**Comment by goelvidhi** [comment]
One suggestion,

```
wmax: size of cwnd just before cwnd was reduced in the last congestion event when fast convergence is disabled. However, if fast convergence is enabled, the size may be conditionally reduced based on the current saturation point.
```

**Comment by lisongxu** [comment]
Thanks, Vidhi!

**Comment by lisongxu** [comment]
Just updated. Thanks
