### ISSUE TITLE
linux's cubic fix? (better follow cubic curve after idle period)

### ISSUE THREAD

**Issue by junhochoi** [NTAP/rfc8312bis#57]
http://bitsup.blogspot.com/2015/09/thanks-google-tcp-team-for-open-source.html
https://github.com/torvalds/linux/commit/30927520dbae297182990bb21d08762bcc35ce1d

Does rfc8312bis need to mention/include about this algorithm?

**Comment by lisongxu** [comment]
This is discussed in [Section 5.8](https://ntap.github.io/rfc8312bis/draft-ietf-tcpm-rfc8312bis.html#name-behavior-for-application-li). Thanks

**Comment by junhochoi** [comment]
Indeed. Thanks!
