### ISSUE TITLE
Units are missing or unclear

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#6]
@martinthomson raised this on the QUIC slack:
> What are the units of C?  What are the units of t? (edited) 
I'm assuming that the units of W_cubic(t) and W_max are bytes (or multiples of MSS, I guess).  But what about W_est(t)?
W_est(t) = W_max*0.7 + 1.1 * t / RTT
(Numbers approximated.)  That's a component in bytes, and a unit-less component.

**Comment by lisongxu** [comment]
Copied from the beginning of Section 4: "The unit of all window sizes in this document is segments of the  maximum segment size (MSS), and the unit of all times is seconds."

**Comment by larseggert** [comment]
Right, but are all variables window sizes?

**Comment by lisongxu** [comment]
If I did my math correctly ... 

Unit of C : MSS / (Second^3)
Unit of K : Second

**Comment by goelvidhi** [comment]
I think,
C is 1/ S^3 
t is time in sec
K is time in sec
All Ws are in packets. (W_est is also in packets and packets don't have any units)

**Comment by goelvidhi** [comment]
What would be the best place to add these units? Next to the equation or the section where all variables would be described? (ref. https://github.com/NTAP/rfc8312bis/issues/5)

**Comment by sangtaeha** [comment]
@goelvidhi Where we explain C, t, K, Wmax, etc.?

**Comment by goelvidhi** [comment]
that should we fine too. But there was an issue #5 to define the variables with units. I was thinking to put it all at one place and then remove redundant explanations.

**Comment by larseggert** [comment]
@goelvidhi I think consolidating it as you suggest (e.g., into a table) is probably best.

**Comment by lisongxu** [comment]
@goelvidhi The unit of all windows should be MSS (or segment), and then the unit of C should be MSS / S^3 ? Thanks
