### ISSUE TITLE
Events detected by RACK

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#62]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
>>2: Section 3.1 "After a window reduction in response to a congestion event is
     detected by duplicate ACKs or Explicit Congestion Notification-Echo
     (ECN-Echo, ECE) ACKs [RFC3168], CUBIC remembers the congestion window..."
>
>   I think the events detected by RACK (or PTO for QUIC) can also be included here.

**Comment by goelvidhi** [comment]
thanks @nsdyoshi. Do you have any specific suggestions in terms of how much should we talk about RACK or should we just add a one-liner?

**Comment by nsdyoshi** [comment]
one liner works for me, but, I think the following part in Section 4.6 also needs to be updated.

> When a packet loss is detected by duplicate ACKs or by receiving packets carrying ECE flags, CUBIC updates Wmax and reduces cwnd and ssthresh immediately as described below

**Comment by larseggert** [comment]
Could someone create a PR for this?

**Comment by goelvidhi** [comment]
yes, will send something soon.

**Comment by larseggert** [comment]
@goelvidhi could we get this done by the end of the week, so we can post a new draft on Monday?
