### ISSUE TITLE
'Equation' rather than 'Figure'

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#63]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
>4: Section 4.2  I personally prefer to refer the equations in the draft as 'Equation' rather than 'Figure'  if there's 
    no strong reason for it.

**Comment by goelvidhi** [comment]
Whenever some relevant text is followed by an equation, we refer to it as `formula` or `equation`. But if we are referring to an equation in the later text, then we use the term `figure`. This seems consistent with other sections of the draft.

I do like your advice of changing the figure to equation though. So I will try to change it at all places.

**Comment by goelvidhi** [comment]
@larseggert the text in the raw file uses the below code which shows as Figure 1. Is there an easy way to change this to Equation 1?
> {: #eq1 artwork-align="center" }

**Comment by goelvidhi** [comment]
> With kramdown-xml2rfc2629, it's unfortunately not possible to change this. We would need to add an RFC Editor Note instructing them to manually make the change. Opened https://github.com/NTAP/rfc8312bis/issues/63

Just saw your reply on the email. In that case, I believe we just need to add a note. Do you want to do that?
