### ISSUE TITLE
Two meanings for a_aimd

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#64]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
> 5: Section 4.3  It seems to me that there are two meanings for a_aimd in this section. 
    One is the additive factor for CUBIC and the other is a generic parameter for AIMD() function. 
    This looks a bit confusing to me.

**Comment by goelvidhi** [comment]
Both of these mean the same thing. The additive factor for CUBIC is defined such that the result of AVG_AIMD(alpha_aimd, beta_aimd) for both AIMD like congestion controllers and Cubic is same. 

After making that comparison, the draft basically describes what alpha_aimd is equivalent to for Cubic and since it is represented using B_cubic on the right hand side, I don't think there is a need to define two different alpha_aimd.
<img width="305" alt="Screen Shot 2021-06-03 at 2 39 27 AM" src="https://user-images.githubusercontent.com/10913828/120623819-ed074a00-c414-11eb-92a9-67e910aa8f77.png">

**Comment by larseggert** [comment]
@nsdyoshi does this address your comment?

**Comment by nsdyoshi** [comment]
Sorry. my view is a bit different.
In Section 4.1.1, alpha_aimd is defined as a constant, which is around 0.529
OTOH, alpha_aimd in Figure 3 is a variable. You can set arbitrary value to it.

At least, this is confusing to me. But, I'm fine to keep it if all other folks don't think in this way.
I would like to hear other people's thought a bit more.

**Comment by goelvidhi** [comment]
@Lars I am not sure if other folks are looking at these issues, what's the best way to get their opinion on this?

**Comment by lisongxu** [comment]
@nsdyoshi Thanks, Yoshi. I can see that it is kind of confusing. Section 4.3 describes an analysis of an AIMD algorithm with parameters alpha and beta to explain why and how CUBIC determines its alpha value. We thought about introducing two more variables (alpha, and beta) explicitly for CUBIC, which seem more confusing (too many variables).

**Comment by goelvidhi** [comment]
@nsdyoshi  I have sent this on the list. If no response is received, would you be fine with closing this issue as is?

**Comment by nsdyoshi** [comment]
@goelvidhi yes, fine with me. But, I think we might want to set a certain deadline and notify people.

**Comment by chromi** [comment]
I think the explanation would be clearer if the formula for AVG_AIMD was rewritten using **unsuffixed** α and β parameters, α(aimd) and β(aimd) were used exclusively to refer to the Reno parameters, and α(cubic) and β(cubic) used to refer exclusively to the CUBIC parameters.

The process of calculating α(cubic) can then be explained as equalising the values of AVG_AIMD(α(aimd), β(aimd)) and AVG_AIMD(α(cubic), β(cubic)).

**Comment by goelvidhi** [comment]
I have opened a PR where I use alpha and beta for general equation and further derivation of alpha.
Later I use alpha_cubic to refer to Cubic specifically. Feel free to review and provide comments on the PR.
