### ISSUE TITLE
Description for P is required

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#65]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
> 6: Section 4.3  The description for P is required for Figure 3.

**Comment by lisongxu** [comment]
Thanks, Yoshi, for catching it. P is the packet loss rate. We will describe it in the specification. Thanks

**Comment by larseggert** [comment]
@lisongxu could you create a PR for this?

**Comment by lisongxu** [comment]
Working on it. Thanks
Lisong

________________________________
