### ISSUE TITLE
Analysis in [FHP00] doesn't include delayed ACK factor

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#66]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
> 7: Section 4.3  I think The analysis in [FHP00] doesn't include delayed ACK factor. So, the AIMD TCP model here 
   can be a bit aggressive compared to a TCP that doesn't enable ABC and uses delayed ACK. 
  This is fine, but I think it might be good to clarify it.

**Comment by lisongxu** [comment]
Thanks, Yoshi. Yes, we can clarify this in the specification.

**Comment by larseggert** [comment]
@lisongxu could you create a PR for this?

**Comment by lisongxu** [comment]
Sure, working on it. Sorry for the delay.
Lisong

________________________________
