### ISSUE TITLE
segments_acked rather than bytes_acked; cwnd in segments

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#67]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
>8: Section 4.3  I am not very sure why segments_acked is used rather than byted_acked here. What is the benefit of it?
    How do we calculate when the acks are split? 
   Also, I think it should be clarified that cwnd is expressed in segments here in this case.

**Comment by goelvidhi** [comment]
segments_acked is used throughout the document to match the linux code.

Section 4.1.2 (https://datatracker.ietf.org/doc/html/draft-ietf-tcpm-rfc8312bis-02#section-4.1.2) defines the units for all variables including `cwnd` which is in segments.

> How do we calculate when the acks are split?
I am guessing that this problem has already been solved in linux.

**Comment by larseggert** [comment]
@nsdyoshi does this address your comment?

**Comment by nsdyoshi** [comment]
Ok. I see the definition in cwnd. I'm sorry, I overlooked.
But, my main question is why segments_acked is used and byte_acked is not used.  I believe we don't need to follow linux code.
Some implementations may want to use byted_acked. Is it allowed? I think it would be better to provide some guidance here.

**Comment by goelvidhi** [comment]
Yes, implementations can use bytes_acked. Does the below text suffice:
> The unit of all window sizes in this document is segments of the
maximum segment size (MSS), and the unit of all times is seconds.

**Comment by nsdyoshi** [comment]
I think it would be better to mention using bytes_acked is acceptable for implementations explicitly. 

BTW, when a segments_acked implementation sent a 1000 byte packet and only 500 bytes were acked, does it use fractions or use some other methods? 
Another question is if we count sacked segments into this or not.

**Comment by goelvidhi** [comment]
> BTW, when a segments_acked implementation sent a 1000 byte packet and only 500 bytes were acked, does it use fractions or use some other methods?
If the size of each segment = 1 MSS, then segments_acked = bytes_acked / 1 MSS.

> Another question is if we count sacked segments into this or not.
Good question, is that being done for new Reno or other congestion controllers? I looked at a few RFCs and didn't find any mention of using SACK bytes for congestion window. Do you know if any document has guidance on this?

**Comment by nsdyoshi** [comment]
> If the size of each segment = 1 MSS, then segments_acked = bytes_acked / 1 MSS.
I was wondering the case where the size of segment is not 1 MSS or the case where the size of segment is 1 MSS, but the received ACK covers only part of the segment. It seems to me that this point is a bit ambiguous in the draft.

> Good question, is that being done for new Reno or other congestion controllers?

Right. It's described in RFC6582 and RFC6675. 
I've thought about this and I think the explanation of the draft on this point is sufficient.

**Comment by goelvidhi** [comment]
> I was wondering the case where the size of segment is not 1 MSS or the case where the size of segment is 1 MSS, but the received ACK covers only part of the segment. It seems to me that this point is a bit ambiguous in the draft.

If I were to use segments_acked as an implementor, I would just do bytes_acked / 1 MSS, whatever may be the size of the segment sent or ACKed. For example if MSS = 1448 and 1000 byte segment was sent and acked, then segments_acked = 1000/1448 and if 500 bytes were acked, then segments_acked = 500/1448.

If OTOH I was using bytes_acked in my implementation, then all one needs to do multiple or divide by 1MSS wherever necessary.

**Comment by nsdyoshi** [comment]
OK. In this case, I think it would be better to mention segments_acked is float number and can be less than 1.
Also, I think it would be good to provide a guidance for an implementation uses bytes_acked instead of segments_acked.
Something like multiplying segment-based parameters by 1 MSS.

**Comment by goelvidhi** [comment]
ok, please review #77.
