### ISSUE TITLE
Keeping w_max and reducing only cwnd

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#70]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
>>11: Section 4.7: "we update w_max as follows, before the window reduction as described in section 4.6"
>
>   I am wondering if reducing w_max is the right approach here. Because if we reduce w_max, CUBIC
   can exit from convex region earlier than the case where fast convergence is not used. 
   It seems to me that keeping w_max and reducing only cwnd (using smaller value than b_cubic) 
   look more conservative.

**Comment by goelvidhi** [comment]
> [Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
> 
> > > 11: Section 4.7: "we update w_max as follows, before the window reduction as described in section 4.6"
> > 
> > 
> > I am wondering if reducing w_max is the right approach here. Because if we reduce w_max, CUBIC
> > can exit from convex region earlier than the case where fast convergence is not used.
> > It seems to me that keeping w_max and reducing only cwnd (using smaller value than b_cubic)
> > look more conservative.

Did you mean that it will exit the concave region earlier, and yes that's the intention. The point is to increase the time for this flow to increase its congestion window in order to release bandwidth to any potential new flows. In the below figure, the S curve is due to fast convergence by reducing W_max and you can see that it takes longer to grow congestion window that way as the flow will switch to convex side faster.
![Cubic_curve](https://user-images.githubusercontent.com/10913828/120626158-3f496a80-c417-11eb-83be-60922e78a32c.png)

**Comment by larseggert** [comment]
@nsdyoshi does this address your comment?

**Comment by nsdyoshi** [comment]
I did some comparisons for this. The green line is the w_cubic without fast convergence. The blue line is the w_cubic with fast convergence proposed in the draft. The red line is the one I proposed.

As you can see, the blue line is more conservative when cwnd is closed to w_max while it's a little bit more aggressive than w_cubic without fast convergence when cwnd is very high. 
My proposed method is not very conservative when cwnd is closed to w_max while it's a bit conservative when cwnd is very high. 

I think the behavior of current fast convergence algorithm is much better than what I proposed. 
Although It becomes a bit aggressive when cwnd is very high, I personally think this point is not very important.

![image](https://user-images.githubusercontent.com/73777040/120921805-5936b780-c67a-11eb-8362-5a97d15304c3.png)

**Comment by larseggert** [comment]
@nsdyoshi ok, so can this issue be closed with no action?

**Comment by nsdyoshi** [comment]
Yes, I'm fine with it.
