### ISSUE TITLE
Results are based on the algorithms

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#71]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
>12: Section 5.2 and Section 5.3. Do these results are based on the algorithms and the parameter values 
   described in the draft?  If there're differences, I think it should be described.

**Comment by lisongxu** [comment]
@nsdyoshi Thanks, Yoshi. I guess you refer to the tables in Sections 5.1 and 5.2. Yes they are calculated for the algorithm and parameters described in the draft, and the source code to generate these tables is available on the github.

**Comment by goelvidhi** [comment]
@nsdyoshi is there any action item here?

**Comment by nsdyoshi** [comment]
Oh. sorry. I forgot to reply this one. If there's no difference, it's fine for me. 
In my understanding, the CUBIC in the original paper uses b_cubic=0.8. So, if the values in the tables were created when the paper was written, the values might not be very accurate.

**Comment by larseggert** [comment]
We should probably say that these values are for the current version of CUBIC.

**Comment by lisongxu** [comment]
Yes, the tables have been updated, and source code to generate the tables is available on github. Thanks

**Comment by larseggert** [comment]
Propose to close with no action. OK, @nsdyoshi?

**Comment by nsdyoshi** [comment]
I'm fine with no action.
