### ISSUE TITLE
Discussion in Sec 5. brings up surprisingly little data

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#91]
[Markku Kojo said](https://mailarchive.ietf.org/arch/msg/tcpm/nd4Af8QRQMDkp_R_9ZQMkI4yGAc):
> I regret to say that the discussion in Sec 5. brings up surprisingly little data to back up the claims that are made. Given the long deployment experience that is emphasised in the draft, there, however, is little evidence (measurement data) summarised and cited to back up the claims. "There is a long deployment experience" does not provide any evidence as such. There should be a lot of studies with measurement data accumulated over the years that would support the assertions in the doc. Or, is there?

**Comment by larseggert** [comment]
@lisongxu, any update?

**Comment by larseggert** [comment]
@lisongxu ping

**Comment by sangtaeha** [comment]
@larseggert @lisongxu We have maintained a website for more than 10 years (2005 - 2016) showing the performance of CUBIC over many different networks. That site is gone now. I will try to find a comprehensive measurement study instead.

**Comment by sangtaeha** [comment]
@lisongxu We have a COMNET paper that evaluates CUBIC along with the other protocols w/ and w/o background traffic. Our INFOCOM convex ordering paper shows evidence of its stability.  Another COMNET paper "Taming the elephant.." also has real-world results as well. Adding a few experimental study papers after that may be enough.

**Comment by larseggert** [comment]
@lisongxu/@sangtaeha  could we get a PR for this, please?

**Comment by lisongxu** [comment]
@larseggert I will get a PR this weekend. Thanks
